- name: Kubernetes Cluster Setup
  hosts: master
  become: yes
  tasks:
    - name: Initialize Kubernetes Master
      command: kubeadm init --pod-network-cidr=100.100.100.0/24 --cri-socket=unix:///run/containerd/containerd.sock
      register: kubeadm_init_output
      changed_when: "'Your Kubernetes control-plane has initialized' in kubeadm_init_output.stdout"

    - name: Extract Join Command
      shell: kubeadm token create --print-join-command
      register: join_command
      changed_when: false

    - name: Save Join Command to a file
      copy:
        content: "{{ join_command.stdout }}"
        dest: /tmp/k8s_join_command.txt

- name: Join Worker Nodes to Cluster
  hosts: worker
  become: yes
  tasks:
    - name: Fetch Join Command from Master
      fetch:
        src: /tmp/k8s_join_command.txt
        dest: ./k8s_join_command.txt
        flat: yes

    - name: Run Join Command
      command: "{{ lookup('file', './k8s_join_command.txt') }}"
      register: join_result
      changed_when: "'This node has joined the cluster' in join_result.stdout"
