apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-deployment
spec:
  selector:
    matchLabels:
      app: board
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
        - name: board
          image: cksdudtj/board:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: configmap
            - secretRef:
                name: secret