apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-deployment
spec:
  selector:
    matchLabels:
      app: reservation
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation
          image: cksdudtj/reservation:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: configmap
            - secretRef:
                name: secret