apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
spec:
  selector:
    matchLabels:
      app: search
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: cksdudtj/search:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: configmap
            - secretRef:
                name: secret