apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: cksdudtj/user:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: configmap
            - secretRef:
                name: secret